// apps/api/src/services/GrowthAnalytics.ts
import { eq } from 'drizzle-orm';
import type { GrowthStats } from '@acsf/shared';
import type { ServiceContext } from '../context';
import * as schema from '../db/schema';

/**
 * Growth analytics (§31) — computed exclusively from completed orders and
 * their cart line items. No product is named anywhere in this file: the anchor
 * is whichever product actually sold the most, and the co-purchase rates are
 * counted from real cart lines.
 *
 * The orders it reads are generated by DemoService's history bootstrap, which
 * anchors on whatever product the user's intent resolved to — so this tab
 * follows the intent rather than a seeded shoe/sock pair. The bootstrap's
 * SHAPE (how many orders, how many paired) is a designed fixture; the rates
 * here are arithmetic over whatever that shape produced.
 */
export class GrowthAnalyticsService {
  constructor(private readonly ctx: ServiceContext) {}

  compute(): GrowthStats[] {
    const orders = this.ctx.db
      .select()
      .from(schema.orders)
      .where(eq(schema.orders.status, 'completed'))
      .all();
    if (orders.length === 0) return [];

    const products = new Map(this.ctx.catalog.listProducts().map((p) => [p.id, p]));
    const orderLines = orders.map((order) => ({
      order,
      items: this.ctx.db
        .select()
        .from(schema.cartItems)
        .where(eq(schema.cartItems.cartId, order.cartId))
        .all(),
    }));

    const orderCounts = new Map<string, number>();
    for (const { items } of orderLines) {
      for (const pid of new Set(items.map((item) => item.productId))) {
        orderCounts.set(pid, (orderCounts.get(pid) ?? 0) + 1);
      }
    }

    // Anchor = best-selling product; deterministic tie-break by productId.
    let anchor: { id: string; count: number } | null = null;
    for (const [pid, count] of [...orderCounts.entries()].sort((a, b) =>
      a[0].localeCompare(b[0]),
    )) {
      if (count > (anchor?.count ?? 0)) {
        anchor = { id: pid, count };
      }
    }
    if (anchor === null) return [];
    const anchorId = anchor.id;
    const anchorProduct = products.get(anchorId);
    if (anchorProduct === undefined) return [];

    const anchorOrders = orderLines.filter(({ items }) =>
      items.some((item) => item.productId === anchorId),
    );
    if (anchorOrders.length === 0) return [];

    const co = new Map<string, { count: number; revenuePaise: number; marginPercent: number }>();
    for (const { items } of anchorOrders) {
      const seen = new Set<string>();
      for (const item of items) {
        if (item.productId === anchorId || seen.has(item.productId)) continue;
        seen.add(item.productId);
        const entry = co.get(item.productId) ?? { count: 0, revenuePaise: 0, marginPercent: 0 };
        entry.count += 1;
        entry.revenuePaise += item.unitPricePaise * item.quantity;
        // The margin frozen onto the line at the time of sale. Rows written
        // before cart_items.margin_percent existed carry 0; fall back to the
        // catalog for those rather than reporting a margin of zero.
        entry.marginPercent =
          item.marginPercent > 0 ? item.marginPercent : (products.get(item.productId)?.marginPercent ?? 0);
        co.set(item.productId, entry);
      }
    }

    return [...co.entries()]
      .map(([pid, entry]): GrowthStats => {
        const product = products.get(pid);
        return {
          productIdA: anchorId,
          productNameA: anchorProduct.name,
          productIdB: pid,
          productNameB: product?.name ?? pid,
          coPurchaseRate: Math.round((entry.count / anchorOrders.length) * 100) / 100,
          avgUpsellPaise: Math.round(entry.revenuePaise / entry.count),
          marginPercent: entry.marginPercent,
          conversionCount: entry.count,
          revenueContributionPaise: entry.revenuePaise,
        };
      })
      .sort((a, b) => b.coPurchaseRate - a.coPurchaseRate || a.productIdB.localeCompare(b.productIdB));
  }

  top(): GrowthStats | null {
    return this.compute()[0] ?? null;
  }
}