// apps/api/src/services/index.ts  (MODIFIED — full reprint)
export { CatalogService, toProductDTO } from './CatalogService';
export type { ResolvedCartItem, ItemResolution } from './CatalogService';
export { CatalogAdminService, ProductCreateSchema, ProductUpdateSchema } from './CatalogAdminService';
export type { ProductCreateInput, ProductUpdateInput } from './CatalogAdminService';
export { AuditService } from './AuditService';
export type { AppendAuditInput, AuditListOptions } from './AuditService';
export { MandateService, MandateCreateSchema } from './MandateService';
export type { MandateCreateInput, MandateView } from './MandateService';
export { CapabilityService } from './CapabilityService';
export { PolicyEngine, PolicyPatchSchema } from './PolicyEngine';
export type { PolicyPatch } from './PolicyEngine';
export { CartIntegrityService } from './CartIntegrityService';
export type { CanonicalCartItem, CartLine } from './CartIntegrityService';
export { AuthorityDriftEngine } from './AuthorityDriftEngine';
export type { AttemptRecord } from './AuthorityDriftEngine';
export { CartService } from './CartService';
export type { CartLineItem, CartView, CreateCartInput } from './CartService';
export { AuthorizationEngine } from './AuthorizationEngine';
export type { AuthorizationResult, PaymentPlan, ModifyPlan } from './AuthorizationEngine';
export { PaymentService } from './PaymentService';
export type { ProviderEventResult } from './PaymentService';
export { PaymentReconciliationService } from './PaymentReconciliationService';
export { MetricsService } from './MetricsService';
export { GrowthAnalyticsService } from './GrowthAnalytics';
export { GrowthAgent } from './GrowthAgent';
export type { GrowthProposeInput } from './GrowthAgent';
export { BuyerAgent, intentTokens } from './BuyerAgent';
export { AdversarialAgent } from './AdversarialAgent';
export { DemoService } from './DemoService';
export type { DemoRunOptions } from './DemoService';
export { IntentService } from './IntentService';
export type { IntentPlanOverrides } from './IntentService';
export { CounterfactualService } from './CounterfactualService';
export type { CounterfactualInput } from './CounterfactualService';
export { FuzzerService } from './FuzzerService';
export type { FuzzerRunInput, FuzzerRunOutput } from './FuzzerService';
export { AttackService } from '../attacks';